
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - fleet_network

  web:
    build: .
    command: gunicorn vehicle_fleet.wsgi:application -c gunicorn_config.py
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - 8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
    networks:
      - fleet_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - fleet_network

volumes:
  postgres_data:
  static_volume:

networks:
  fleet_network:
    driver: bridge