# Generated by Django 5.2.15 on 2026-06-11 18:55

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=25)),
                ('registered_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-status', 'registered_number', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('license_number', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-status', 'name', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('number_of_trips', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pick_up', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_off', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_fill', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('last_reason_to_change', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTripLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('date_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_updated', models.DateTimeField(blank=True, editable=False)),
                ('number_of_trips', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pick_up', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_off', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_fill', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('last_reason_to_change', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'verbose_name': 'historical trip log',
                'verbose_name_plural': 'historical trip logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
