# Generated by Django 5.2.14 on 2026-05-19 09:24

import simple_history.models
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-status', 'name', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTripLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False)),
                ('date_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('number_of_trips', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pick_up', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_off', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_fill', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical trip log',
                'verbose_name_plural': 'historical trip logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('number_of_trips', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_traveled', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pick_up', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_off', models.CharField(blank=True, max_length=100, null=True)),
                ('diesel_fill', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=25)),
                ('registered_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-status', 'registered_number', '-date_created'],
            },
        ),
    ]
