# Generated by Django 5.2.14 on 2026-05-19 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='link to user account if driver needs login access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltriplog',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='historicaltriplog',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triplog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='triplog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='historicaltriplog',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='primary_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
