# Generated by Django 5.2 on 2026-08-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.vehicle'),
        ),
    ]
