# Generated by Django 5.2.12 on 2026-03-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-status', 'name', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='triplog',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-status', 'registered_number', '-date_created']},
        ),
    ]
