# Generated by Django 5.2.17 on 2026-09-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_triplog_driver_alter_triplog_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='triplog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle'),
        ),
    ]
