# Generated by Django 5.2.14 on 2026-05-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_triplog_is_approved_historicaltriplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='primary_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
