"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import sys
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG', cast=bool)

# TESTING = 'test' in sys.argv or 'pytest' in sys.argv

SECRET_KEY = config(
    'SECRET_KEY', default='p)lc1=1&8cq%9vz-sa47*^57iq2s(m%)xwmsyq1v077c#+b=2^', cast=str)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'users',
    'fleet',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='fleet_db', cast=str),
        'USER': config('DB_USER', default='fleet_user', cast=str),
        'PASSWORD': config('DB_PASSWORD', default='fleetpass123', cast=str),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432', cast=str),
    }
}

AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 1. First priority: Look for the HttpOnly cookie (React Production/Dev)
        'config.authentication.CustomJWTAuthentication',
        # 2. Third priority: Fallback to session cookies (Django Admin panel & browsable API)
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'VERSION_PARAM': 'version',

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',  # Anonymous users
        'user': '1000/day'  # Authenticated users
    },

}

SPECTACULAR_SETTINGS = {
    'TITLE': 'FLEET-LOGGER-API',
    'DESCRIPTION': 'Automated interactive API documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]',
}

# ── CORS ──────────────────────────────────────
# Production: Use specific allowed origins
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS', default='http://localhost:8080,http://127.0.0.1:8080', cast=Csv())

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS', default='None', cast=Csv())

# Development fallback (comment this out for production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

SESSION_COOKIE_DOMAIN = config(
    'SESSION_COOKIE_DOMAIN', default='localhost', cast=str)

CSRF_COOKIE_DOMAIN = config(
    'CSRF_COOKIE_DOMAIN', default='localhost', cast=str)

# httponly so js script cant read them onyl http can.
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # MUST be False so your frontend can read it

# --- ENVIRONMENT SPECIFIC CONFIGURATION ---
if not DEBUG:
    # PRODUCTION (OCI + Cloudflare + Vercel)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = "DENY"

    # set secure for https only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Required for Cross-Origin requests between ://domain.com and ://domain.com
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    # (Uncomment these once your production SSL is fully tested and verified via Cloudflare)
    # SECURE_SSL_REDIRECT = True
    # SECURE_BROWSER_XSS_FILTER = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True
else:
    # LOCAL DEVELOPMENT (Docker / localhost)
    # Turn off secure HTTPS requirements for local plain HTTP traffic
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # Use 'Lax' locally so your local frontend (e.g., port 3000) can receive
    # cookies from your local backend container (e.g., port 8000) over HTTP
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django.security.csrf': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

SIMPLE_JWT = {
    "SIGNING_KEY": config("JWT_SECRET_KEY", cast=str),
    # Optional: You can explicitly declare the algorithm (HS256 is default)
    "ALGORITHM": config("HS256", default='HS256', cast=str),

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(config('ACCESS_TOKEN_LIFETIME', default=10, cast=int))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(config('REFRESH_TOKEN_LIFETIME', default=1, cast=int))),
    'ROTATE_REFRESH_TOKENS': config('ROTATE_REFRESH_TOKENS', default=True, cast=bool),
    'BLACKLIST_AFTER_ROTATION': config('BLACKLIST_AFTER_ROTATION', default=True, cast=bool),

    # Custom Cookie Configuration Variables
    'AUTH_COOKIE': config('AUTH_COOKIE', default='access_token', cast=str),
    'AUTH_COOKIE_REFRESH': config('AUTH_COOKIE_REFRESH', default='refresh_token', cast=str),
    # False for local HTTP development, True for Production HTTPS
    'AUTH_COOKIE_SECURE': config('AUTH_COOKIE_SECURE', default=False, cast=bool),
    # Prevents JavaScript reading the cookie (Mitigates XSS)
    'AUTH_COOKIE_HTTP_ONLY': config('AUTH_COOKIE_HTTP_ONLY', default=True, cast=bool),
    'AUTH_COOKIE_PATH': config('AUTH_COOKIE_PATH', default='/', cast=str),
    # Protects against CSRF attacks
    'AUTH_COOKIE_SAMESITE': config('AUTH_COOKIE_SAMESITE', default='Lax', cast=str),
    # 'AUTH_COOKIE_DOMAIN': config('AUTH_COOKIE_DOMAIN'),
}
